/* Generated by cbindgen — do not edit */

#ifndef LIBMNFTS_H
#define LIBMNFTS_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result code returned by all FFI functions.
 */
typedef enum mnfts_MnftsResult {
  OK = 0,
  ERR_IO = 1,
  ERR_NOT_NTFS = 2,
  ERR_DIRTY_VOLUME = 3,
  ERR_HIBERNATED = 4,
  ERR_UNSUPPORTED_VERSION = 5,
  ERR_HEALTH_CHECK = 6,
  ERR_NULL_POINTER = 7,
  ERR_INTERNAL = 99,
} mnfts_MnftsResult;

/**
 * Returns MnftsResult::Ok. Used to verify FFI linkage works.
 */
enum mnfts_MnftsResult mnfts_ping(void);

/**
 * Returns the library version as a static C string.
 */
const char *mnfts_version(void);

#endif  /* LIBMNFTS_H */
